### ISSUE TITLE
Code Lab Feedback

### ISSUE THREAD

**Issue by KatieMFritz** [KatieMFritz/codelab-twitter-bootstrap#1]
Hey @chrisvfritz, can you take a look at this? It's [hosted here](http://cuddly-sneeze.surge.sh/).

I'm not sure if I put the site name in the right place - replaced "Brand" in the navbar, but it's an empty link and not an h1. Is that okay?

**Comment by chrisvfritz** [comment]
### Including Bootstrap

It looks like you're including both the minified _and_ unminified CSS in your HTML, which is unnecessary. `bootstrap.css` and `bootstrap.min.css` have the same content, but the minified (`.min.css`) version just has many of the spaces and other unnecessary characters removed so that it's faster for the browser to download. 

It should also be noted that it's not necessary to include a Bootstrap theme. Personally, I think the default one looks nicer than some of the themes you can override with, so try removing the theme file for now. This way, you get a chance playing with "base" Bootstrap.

### Rows and columns

It looks like you have some `col` classes that that aren't wrapped in a container with a `row` class. This is actually necessary for all your content to line up correctly. As a result, you can see that the left side of your images doesn't line up with the left side of the text above it.

### Mobile-first columns

The `col-xs-12 col-lg-6` classes together suggest that the mobile-first columns may need a little more explaining, so here it is. :smiley: 

When Bootstrap says that it's _mobile-first_, it means that you have to specify when columns _shouldn't_ go full width, taking up the entire 12 columns in the grid. This means that when you apply a class like `col-md-6`, it's the same as applying `col-lg-6 col-md-6 col-sm-12 col-xs-12`. Anything _larger_ than what you specified (`lg` in this example) also spans the number columns you specified (`6` in this example), unless there's a more specific class to override it (e.g. `col-lg-4`). And anything _smaller_ than what you specified will default to span all 12 columns - again, unless a more specific class exists.

I know it's kind of difficult to wrap your head around at first - it definitely took me a while. Does this make sense?

**Comment by KatieMFritz** [comment]
@chrisvfritz I removed the extra CSS files and I think I fixed the row/column issue. I don't understand what I'm supposed to change with the column classes - can we go over it in person?

**Comment by KatieMFritz** [comment]
boom.

**Comment by chrisvfritz** [comment]
:boom: :shipit:

**Comment by KatieMFritz** [comment]
@chrisvfritz I got the shipit squirrel, but this lesson is still pulsing in my lessons map.

**Comment by chrisvfritz** [comment]
Click on the refresh button and let me know if that fixes it.
